name: nightly-training
on:
  schedule:
    - cron: '0 2 * * *' # 02:00 UTC daily (adjust)
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: python-recs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run trainer
        working-directory: python-recs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          python trainer.py
